### ISSUE TITLE
Implementation questions

### ISSUE THREAD

**Issue by zongronghuang** [chatbotgang/image-map-editor#33]
Hi there, 

I've got a few implementation questions about this project. It would be highly appreciated to have your help :) 

- Should text output in the right-side pane be ordered chronologically (from the earliest to the latest or vice versa)?
- Is it necessary to provide a rubbish-bin icon for each rectangular shape?  Can I omit it and use any other thing that looks like a clickable mini-button?
- Is it necessary to provide an upload icon on the upload-image button in the left-side pane? Can I omit it or use anything to take its place?

**Comment by Joseph7451797** [comment]
Hi,
1. Not mandatory.
2. No need to be a rubbish-bin icon. But you should display a button for the user on mouse hovering.
3. Not necessary. It's up to you to build a UI with better UX.

**Comment by Joseph7451797** [comment]
Close with #34
